name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  # JOB 1: BUILD IMAGE
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6.0.2

      # Kích hoạt BuildKit (bắt buộc để dùng cache-from/to)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to GHCR
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          #Tối uu hóa thời gian build bằng cách sử dụng cache
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # JOB 2: DEPLOY LÊN VPS
  deploy:
    runs-on: ubuntu-24.04
    needs: build-and-push
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Login để có quyền pull (dùng PAT_TOKEN)
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 2. Đi đến thư mục chứa file docker-compose.yml duy nhất trên VPS
            cd /srv/production

            # 3. Pull bản mới nhất (Docker sẽ chỉ pull những service có thay đổi)
            docker compose pull

            # 4. Khởi động các Container
            # --remove-orphans: dọn dẹp các container thừa không có trong file compose
            docker compose up -d --remove-orphans

            # 5. Dọn dẹp Image cũ để tránh đầy ổ cứng VPS
            docker image prune -f
